# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39446b35aa23c8b1d0c3173cfe6d009e7a68e44a85ca68b8d1ba288318c53fb4d0fdc73912370f72907e3e0a5247b8738e8fde5dde07652dd2fba2106d68a967

test:
  secret_key_base: 19885047724c21d3d5e1743296339d677bbc0f7f4329d22f154acdfec3e4396462eaa49ac1553bed60c2110d7e5b8e8641020d84d20f9ced5eff66802788ee34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
